version: '3.8'

services:
  spark-jupyter:
    build: .
    container_name: spark_jupyter
    ports:
      - "8888:8888"    # Jupyter
      - "4040:4040"    # Spark UI — mostra execução dos jobs em tempo real
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data
      - ./output:/home/jovyan/output
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_spark
    environment:
      POSTGRES_USER: spark_user
      POSTGRES_PASSWORD: spark_pass
      POSTGRES_DB: fraud_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
